In [1]:
%load_ext autoreload
%autoreload 2
%load_ext jupyter_black

In [32]:
import polars as pl
from tabseq_torch.datasets.alfa import dc, load, meta, prep, raw_data_catalog

In [22]:
raw_data_catalog.scoring_trx.exists()

True

In [25]:
load()

load data from: https://huggingface.co/datasets/dllllb/alfa-scoring-trx
to: /home/jovyan/data/tabseq/raw

In [26]:
prep()

In [27]:
pl.scan_parquet(dc.num).head(3).collect()

shape: (3, 21)
┌────────┬──────────┬──────────┬────────────┬───┬────────────┬───────────┬────────────┬────────────┐
│ app_id ┆ amnt     ┆ currency ┆ operation_ ┆ … ┆ weekofyear ┆ hour_diff ┆ transactio ┆ __index_le │
│ ---    ┆ ---      ┆ ---      ┆ kind       ┆   ┆ ---        ┆ ---       ┆ n_number   ┆ vel_0__    │
│ i32    ┆ f64      ┆ i32      ┆ ---        ┆   ┆ i32        ┆ i64       ┆ ---        ┆ ---        │
│        ┆          ┆          ┆ i32        ┆   ┆            ┆           ┆ i32        ┆ i64        │
╞════════╪══════════╪══════════╪════════════╪═══╪════════════╪═══════════╪════════════╪════════════╡
│ 0      ┆ 0.465425 ┆ 1        ┆ 4          ┆ … ┆ 34         ┆ -1        ┆ 1          ┆ 0          │
│ 0      ┆ 0.0      ┆ 1        ┆ 2          ┆ … ┆ 34         ┆ 0         ┆ 2          ┆ 1          │
│ 0      ┆ 0.521152 ┆ 1        ┆ 2          ┆ … ┆ 34         ┆ 0         ┆ 3          ┆ 2          │
└────────┴──────────┴──────────┴────────────┴───┴────────────┴───────────┴────────────┴────────────┘

In [28]:
dc.targets

PosixPath('/home/jovyan/data/tabseq/raw/alfa-scoring-trx/train_target.csv.gz')

In [29]:
pl.scan_csv(dc.targets).head(3).collect()

shape: (3, 3)
┌────────┬─────────┬──────┐
│ app_id ┆ product ┆ flag │
│ ---    ┆ ---     ┆ ---  │
│ i64    ┆ i64     ┆ i64  │
╞════════╪═════════╪══════╡
│ 0      ┆ 3       ┆ 0    │
│ 1      ┆ 1       ┆ 0    │
│ 2      ┆ 1       ┆ 0    │
└────────┴─────────┴──────┘

In [ ]:
dc.show()